# Network Topology

control0:
  type: control
  description: Data hub

listener0:
  type: listener
  description: Patient room 0
  broker: control0
  sim_data_dir: 'samples/DEV-03 sample 1A  NORMAL-  NORMAL RHYTHM + GOOD NORMOXIC PLETH   (5min NSR + 100% SpO2)'

listener1:
  type: listener
  description: Patient room 1
  broker: control0
  sim_data_dir: 'samples/DEV-03 sample 1D  TRUE POSITIVE-  VTACH + GOOD NORMOXIC PLETH   (5min VT + 98% SpO2 [last half of tracing])'

display0:
  type: display
  broker: control0
  node: listener1

---

# Rules

---

# Alert Zones

zone0:
  nodes: [listener0]
  priorities: [HIGH, MAX]
  number: shadow
  carrier: shadow
