# Set an environment variable for $SPLUNK_PWORD

splunk:
  image: outcoldman/splunk
  hostname: splunk
  volumes:
    - /opt/splunk/etc
    - /opt/splunk/var
  ports:
    - 8000:8000
    - 8089:8089

  environment:
    SPLUNK_START_ARGS: '--accept-license'
    SPLUNK_CMD_1: "edit user admin -password '${SPLUNK_PWORD}' -role admin -auth admin:changeme"
    SPLUNK_CMD_2: "add index perseus -auth 'admin:${SPLUNK_PWORD}'"


# To load sample data automatically:
# $ docker cp samples/x00-01-06232016b.json dockersplunk_splunk_1:/sample.json
# $ docker exec dockersplunk_splunk_1 /opt/splunk/bin/splunk add oneshot "/sample.json" -sourcetype _json -index perseus -host sample1 -auth admin:${SPLUNK_PWORD}
#
# For data files that don't have timestamp at the front of each message, you may need
# to manually change the timestamp extraction for _json to look for the "timestamp" field